# a =5 
# b = 8
# print(a+b)


# # reminder finder

# x =15
# y = 4
# print(x%y)

# # check variable data type

# data = input('enter any type of data : ')
# print(type(data))

# # comparison operator
# a=34
# b=80
# print(a>b)

# average finder
# a = int(input('enter first number'))
# b = int(input('enter second number'))


# print((a+b)/2)

# square of a number

x = int(input('enter a number'))

print('square of given number is : ',x*x)